### ISSUE TITLE
Different Vendor ID

### ISSUE THREAD

**Issue by lensdigital** [mike42/missile#5]
Would you be able to add support for O.I.C. Storm Launcher?  Vendor ID 0x2123, product ID 0x1010
I've tried modifying it in 40-rocketlauncher.rules but it still can't detect it... 

Thank you! :)

**Comment by mike42** [comment]
Hi @lensdigital - it would need to go in the example code, which is [hard-coded to work with only one vendor ID](https://github.com/mike42/missile/blob/4ef94214c1101066547a013aefee5880de2cca12/examples/keyboard-ctl/keyboard-ctl.cpp#L73)

I'm open to reviewing pull requests that implement enumeration of devices to match a list of ID's, but I don't currently have multiple launchers, so I'm not likely to work on it myself.
